#!/usr/bin/env python3
import requests
import time
import sign
import sys

name, num = None, None

if len(sys.argv) >= 2:
    name = sys.argv[1]

if len(sys.argv) >= 3:
    num = sys.argv[2]

display = sign.Sign("dash", 8800)

if name == "--cancel":
    display.remove_message("callerid_name")
    display.remove_message("callerid_num")
    requests.get("http://idiotic/api/item/alert_beacon/command/off")
    time.sleep(5)
else:
    requests.get("http://idiotic/api/item/alert_beacon/command/on")
    if name:
        display.new_message(name, name="callerid_name", effects=["bounce_x"], priority=2, lifetime=30)
    if num:
        display.new_message(num, name="callerid_num", priority=2, lifetime=30)
    if not num and not name:
        display.new_message("UNKNOWN", name="callerid_name", priority=2, lifetime=30)
